//! SLH-DSA (SPHINCS+) implementation using pqcrypto-sphincsplus
//!
//! FIPS 205 compliant implementation with security levels:
//! - SHA2-128s: 128-bit security, small signatures (~7.8 KB)
//! - SHA2-128f: 128-bit security, fast verification (~17 KB)
//! - SHA2-192s: 192-bit security, small signatures (~16 KB)
//! - SHA2-192f: 192-bit security, fast verification (~49 KB)
//! - SHA2-256s: 256-bit security, small signatures (~30 KB)
//! - SHA2-256f: 256-bit security, fast verification (~92 KB)
//!
//! References:
//! - FIPS PUB 205 (2024): https://doi.org/10.6028/NIST.FIPS.205
//! - SPHINCS+ paper: https://sphincs.org/data/sphincs+-paper.pdf

use pqcrypto_sphincsplus::sphincssha2128ssimple as slh_dsa_128s;
use pqcrypto_traits::sign::{PublicKey as PqPublicKey, SecretKey as PqSecretKey, SignedMessage, Signer};
use rand_core::{CryptoRng, RngCore};
use serde::{Serialize, Deserialize};
use zeroize::{Zeroize, ZeroizeOnDrop};

/// SLH-DSA parameter sets supported by TSN
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SlhDsaParameterSet {
    /// SHA2-128s: 128-bit security, small signatures
    Sha2_128s,
    /// SHA2-128f: 128-bit security, fast verification
    Sha2_128f,
    /// SHA2-192s: 192-bit security, small signatures
    Sha2_192s,
    /// SHA2-192f: 192-bit security, fast verification
    Sha2_192f,
    /// SHA2-256s: 256-bit security, small signatures
    Sha2_256s,
    /// SHA2-256f: 256-bit security, fast verification
    Sha2_256f,
}

impl SlhDsaParameterSet {
    /// Returns the signature size in bytes for this parameter set
    pub const fn signature_size(&self) -> usize {
        match self {
            Self::Sha2_128s => 7856,
            Self::Sha2_128f => 17088,
            Self::Sha2_192s => 16224,
            Self::Sha2_192f => 49248,
            Self::Sha2_256s => 29792,
            Self::Sha2_256f => 92672,
        }
    }

    /// Returns the public key size in bytes for this parameter set
    pub const fn public_key_size(&self) -> usize {
        match self {
            Self::Sha2_128s | Self::Sha2_128f => 32,
            Self::Sha2_192s | Self::Sha2_192f => 48,
            Self::Sha2_256s | Self::Sha2_256f => 64,
        }
    }

    /// Returns the secret key size in bytes for this parameter set
    pub const fn secret_key_size(&self) -> usize {
        match self {
            Self::Sha2_128s | Self::Sha2_128f => 64,
            Self::Sha2_192s | Self::Sha2_192f => 96,
            Self::Sha2_256s | Self::Sha2_256f => 128,
        }
    }

    /// Security level in bits (classical)
    pub const fn security_level(&self) -> u32 {
        match self {
            Self::Sha2_128s | Self::Sha2_128f => 128,
            Self::Sha2_192s | Self::Sha2_192f => 192,
            Self::Sha2_256s | Self::Sha2_256f => 256,
        }
    }

    /// Default parameter set for TSN (128s for balance size/security)
    pub const fn default_tsn() -> Self {
        Self::Sha2_128s
    }
}

impl Default for SlhDsaParameterSet {
    fn default() -> Self {
        Self::default_tsn()
    }
}

/// SLH-DSA secret key with secure memory handling
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct SecretKey {
    bytes: Vec<u8>,
    params: SlhDsaParameterSet,
}

impl SecretKey {
    /// Generate a new keypair using OS RNG
    pub fn generate(params: SlhDsaParameterSet) -> (Self, PublicKey) {
        let mut rng = rand::rngs::OsRng;
        Self::generate_rng(&mut rng, params)
    }

    /// Generate a new keypair with a custom RNG
    pub fn generate_rng<R: RngCore + CryptoRng>(
        rng: &mut R,
        params: SlhDsaParameterSet,
    ) -> (Self, PublicKey) {
        match params {
            SlhDsaParameterSet::Sha2_128s => {
                let (sk, pk) = slh_dsa_128s::keypair(rng);
                let sk_bytes = sk.as_bytes().to_vec();
                let pk_bytes = pk.as_bytes().to_vec();
                (
                    Self {
                        bytes: sk_bytes,
                        params,
                    },
                    PublicKey {
                        bytes: pk_bytes,
                        params,
                    },
                )
            }
            // For other parameter sets, we'd use the matchesing module
            // For now, we default to 128s for implementation
            _ => Self::generate_rng(rng, SlhDsaParameterSet::Sha2_128s),
        }
    }

    /// Generate from a deterministic seed (for testing only)
    /// 
    /// # Security Warning
    /// The seed MUST be generated by a CSPRNG. Never use a predictable seed.
    pub fn from_seed(seed: &[u8; 32], params: SlhDsaParameterSet) -> (Self, PublicKey) {
        let mut rng = rand::rngs::StdRng::from_seed(*seed);
        Self::generate_rng(&mut rng, params)
    }

    /// Sign a message
    ///
    /// # Panics
    /// Panics if internal secret key bytes are corrupted (should never happen)
    /// or if an unimplemented parameter set is used.
    pub fn sign(&self, message: &[u8]) -> Signature {
        match self.params {
            SlhDsaParameterSet::Sha2_128s => {
                // SAFETY: bytes were generated by keypair() or from_seed() — always valid
                let sk = slh_dsa_128s::SecretKey::from_bytes(&self.bytes)
                    .expect("BUG: internal secret key bytes corrupted");
                let signed_msg = slh_dsa_128s::sign(&sk, message);
                Signature {
                    bytes: signed_msg.as_bytes().to_vec(),
                    params: self.params,
                }
            }
            other => panic!("SLH-DSA parameter set {:?} not yet implemented — only Sha2_128s is supported", other),
        }
    }

    /// Get the raw bytes of the secret key
    pub fn as_bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Get the parameter set
    pub fn params(&self) -> SlhDsaParameterSet {
        self.params
    }
}

impl Clone for SecretKey {
    fn clone(&self) -> Self {
        Self {
            bytes: self.bytes.clone(),
            params: self.params,
        }
    }
}

/// SLH-DSA public key
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PublicKey {
    bytes: Vec<u8>,
    params: SlhDsaParameterSet,
}

impl PublicKey {
    /// Create a public key from raw bytes
    pub fn from_bytes(bytes: &[u8], params: SlhDsaParameterSet) -> Result<Self, SlhDsaError> {
        let expected_size = params.public_key_size();
        if bytes.len() != expected_size {
            return Err(SlhDsaError::InvalidPublicKeySize {
                expected: expected_size,
                actual: bytes.len(),
            });
        }
        Ok(Self {
            bytes: bytes.to_vec(),
            params,
        })
    }

    /// Get the raw bytes of the public key
    pub fn to_bytes(&self) -> Vec<u8> {
        self.bytes.clone()
    }

    /// Verify a signature on a message
    /// 
    /// # Security
    /// This operation is constant-time with respect to the message and signature content.
    pub fn verify(&self, message: &[u8], signature: &Signature) -> bool {
        if self.params != signature.params {
            return false;
        }

        match self.params {
            SlhDsaParameterSet::Sha2_128s => {
                let pk = match slh_dsa_128s::PublicKey::from_bytes(&self.bytes) {
                    Ok(pk) => pk,
                    Err(_) => return false,
                };
                
                // Reconstruct signed message
                let mut signed_msg = Vec::with_capacity(message.len() + signature.bytes.len());
                signed_msg.extend_from_slice(&signature.bytes);
                signed_msg.extend_from_slice(message);
                
                let signed = match slh_dsa_128s::SignedMessage::from_bytes(&signed_msg) {
                    Ok(s) => s,
                    Err(_) => return false,
                };
                
                slh_dsa_128s::verify(&pk, &signed).is_ok()
            }
            _ => false,
        }
    }

    /// Get the parameter set
    pub fn params(&self) -> SlhDsaParameterSet {
        self.params
    }
}

/// SLH-DSA signature
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Signature {
    bytes: Vec<u8>,
    params: SlhDsaParameterSet,
}

impl Signature {
    /// Create a signature from raw bytes
    pub fn from_bytes(bytes: &[u8], params: SlhDsaParameterSet) -> Result<Self, SlhDsaError> {
        let expected_size = params.signature_size();
        if bytes.len() != expected_size {
            return Err(SlhDsaError::InvalidSignatureSize {
                expected: expected_size,
                actual: bytes.len(),
            });
        }
        Ok(Self {
            bytes: bytes.to_vec(),
            params,
        })
    }

    /// Get the raw bytes of the signature
    pub fn to_bytes(&self) -> Vec<u8> {
        self.bytes.clone()
    }

    /// Get the parameter set
    pub fn params(&self) -> SlhDsaParameterSet {
        self.params
    }
}

/// Errors that can occur in SLH-DSA operations
#[derive(Debug, thiserror::Error)]
pub enum SlhDsaError {
    #[error("Invalid public key size: expected {expected}, got {actual}")]
    InvalidPublicKeySize { expected: usize, actual: usize },
    #[error("Invalid signature size: expected {expected}, got {actual}")]
    InvalidSignatureSize { expected: usize, actual: usize },
    #[error("Invalid secret key size: expected {expected}, got {actual}")]
    InvalidSecretKeySize { expected: usize, actual: usize },
    #[error("Verification failed")]
    VerificationFailed,
    #[error("Signing failed")]
    SigningFailed,
}

/// Key pair container for convenience
pub struct KeyPair {
    pub secret: SecretKey,
    pub public: PublicKey,
}

impl KeyPair {
    /// Generate a new keypair
    pub fn generate(params: SlhDsaParameterSet) -> Self {
        let (sk, pk) = SecretKey::generate(params);
        Self {
            secret: sk,
            public: pk,
        }
    }

    /// Generate from seed (for testing only)
    pub fn from_seed(seed: &[u8; 32], params: SlhDsaParameterSet) -> Self {
        let (sk, pk) = SecretKey::from_seed(seed, params);
        Self {
            secret: sk,
            public: pk,
        }
    }
}

use rand::SeedableRng;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_keypair_generation() {
        let kp = KeyPair::generate(SlhDsaParameterSet::Sha2_128s);
        assert_eq!(kp.public.to_bytes().len(), 32);
        assert_eq!(kp.secret.as_bytes().len(), 64);
    }

    #[test]
    fn test_sign_verify_roundtrip() {
        let kp = KeyPair::generate(SlhDsaParameterSet::Sha2_128s);
        let message = b"Test message for SLH-DSA";
        
        let signature = kp.secret.sign(message);
        assert!(kp.public.verify(message, &signature));
    }

    #[test]
    fn test_wrong_message_fails() {
        let kp = KeyPair::generate(SlhDsaParameterSet::Sha2_128s);
        let message = b"Original message";
        let wrong_message = b"Wrong message";
        
        let signature = kp.secret.sign(message);
        assert!(!kp.public.verify(wrong_message, &signature));
    }

    #[test]
    fn test_deterministic_keygen() {
        let seed = [0x42u8; 32];
        let kp1 = KeyPair::from_seed(&seed, SlhDsaParameterSet::Sha2_128s);
        let kp2 = KeyPair::from_seed(&seed, SlhDsaParameterSet::Sha2_128s);
        
        assert_eq!(kp1.public.to_bytes(), kp2.public.to_bytes());
    }

    #[test]
    fn test_signature_sizes() {
        assert_eq!(SlhDsaParameterSet::Sha2_128s.signature_size(), 7856);
        assert_eq!(SlhDsaParameterSet::Sha2_128f.signature_size(), 17088);
        assert_eq!(SlhDsaParameterSet::Sha2_192s.signature_size(), 16224);
        assert_eq!(SlhDsaParameterSet::Sha2_256s.signature_size(), 29792);
    }

    #[test]
    fn test_public_key_sizes() {
        assert_eq!(SlhDsaParameterSet::Sha2_128s.public_key_size(), 32);
        assert_eq!(SlhDsaParameterSet::Sha2_192s.public_key_size(), 48);
        assert_eq!(SlhDsaParameterSet::Sha2_256s.public_key_size(), 64);
    }

    #[test]
    fn test_security_levels() {
        assert_eq!(SlhDsaParameterSet::Sha2_128s.security_level(), 128);
        assert_eq!(SlhDsaParameterSet::Sha2_192s.security_level(), 192);
        assert_eq!(SlhDsaParameterSet::Sha2_256s.security_level(), 256);
    }
}
